
package com.jk.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSBookServiceImplService", targetNamespace = "http://impl.cxf.jk.com/", wsdlLocation = "http://localhost:8080/webservice/WSBookServiceImpl?wsdl")
public class WSBookServiceImplService
    extends Service
{

    private final static URL WSBOOKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSBOOKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WSBOOKSERVICEIMPLSERVICE_QNAME = new QName("http://impl.cxf.jk.com/", "WSBookServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/WSBookServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSBOOKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WSBOOKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WSBookServiceImplService() {
        super(__getWsdlLocation(), WSBOOKSERVICEIMPLSERVICE_QNAME);
    }

    public WSBookServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBOOKSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSBookServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WSBOOKSERVICEIMPLSERVICE_QNAME);
    }

    public WSBookServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBOOKSERVICEIMPLSERVICE_QNAME, features);
    }

    public WSBookServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSBookServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSBookService
     */
    @WebEndpoint(name = "WSBookServiceImplPort")
    public WSBookService getWSBookServiceImplPort() {
        return super.getPort(new QName("http://impl.cxf.jk.com/", "WSBookServiceImplPort"), WSBookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSBookService
     */
    @WebEndpoint(name = "WSBookServiceImplPort")
    public WSBookService getWSBookServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.cxf.jk.com/", "WSBookServiceImplPort"), WSBookService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBOOKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WSBOOKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WSBOOKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
